### ISSUE TITLE
fetch_local_hash, fetch_remote_hash return nil

### ISSUE THREAD

**Issue by capicue** [manveru/bundix#1]
I had to edit `fetch_local_hash` and `fetch_remote_hash` to return the hash instead of nil as it's expected by `convert_rubygems` https://github.com/manveru/bundix/blob/37dff29fa77f6963e252de953ec8d1004dea340f/lib/bundix/source.rb#L85

Other than that it's looking great. Any plans for a nixpkgs merge?

**Comment by manveru** [comment]
Could you specify in what case it returns nil? I plan on adding it to nixpkgs as soon as I'm confident that it works for like 99% of Gemfiles... right now for example it still can't handle `Path` sources.

**Comment by zimbatm** [comment]
@manveru path support doesn't need to be a blocked, it's not handled by the bundlerEnv either

**Comment by manveru** [comment]
Alright, let's see, I think 2.0.4 is good enough for inclusion. Gonna prepare a nixpkgs entry.
@capicue would be nice if you could try it once again and let me know how it goes. I removed the useless rubygems API lookup, it was too unreliable. My favorite way to use bundix now is after `bundle pack`.

**Comment by manveru** [comment]
Pending PR for bundix in nixpkgs: https://github.com/NixOS/nixpkgs/pull/12903

**Comment by manveru** [comment]
So PR got merged, closing this issue.

**Comment by capicue** [comment]
Sorry about that, I somehow disabled notifications.

Bundix is working great for me now. Thanks for all of the work!
