### ISSUE TITLE
Using libcurl with a gem

### ISSUE THREAD

**Issue by ianks** [manveru/bundix#16]
I have a project that requires libcurl in one of the gems ([curb](https://github.com/taf2/curb)). Unfortunately, this gem will not build with bundix, and I am unsure how to stitch things together in this case. What is the best practice for dealing with things like this in bundix? Here is a gist of what I have so far:  

https://gist.github.com/ianks/959782e1425a92538624eeee534fc09b

Essentially, the curb gem needs the arguments `--with-curl-dir`, and I am not sure how to make that happen. Any ideas?

**Comment by zimbatm** [comment]
hi @ianks, to inject system dependencies you can do something like that:
```nix
{ bundlerEnv, curl }:
bundlerEnv {
  # ....
  gemConfig.curb = attrs: {
    buildInputs = [ curl ];
    # or
    buildFlags = [ "--with-curl-dir=${curl}" ];
  };
}
```

Inside of nixpkgs we also maintain a set of common overrides. If the fix works well, consider adding it to nixpkgs so everyone can benefit: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ruby-modules/gem-config/default.nix

**Comment by ianks** [comment]
Awesome thank you!
