### ISSUE TITLE
Unable to fetch from dependencies rubygems.org

### ISSUE THREAD

**Issue by ivanbrennan** [manveru/bundix#28]
I'm not sure whether this is an issue with bundix, or bundler (or NixOS or rubygems), but I'm hoping someone can point me in the right direction.

I was previously able to package gems on NixOS. I used `BundlerApp` to package [coderay](https://github.com/rubychan/coderay) and [rouge](https://github.com/jneen/rouge).

I recently updated NixOS from 17.09 to 18.03, which may or may not be related. I can no longer fetch dependencies from rubygems. So far it appears possibly related to [416 (Range Not Satisfiable)](https://github.com/bundler/bundler/pull/5826) responses Bundler is receiving from rubygems.

To illustrate with coderay, a gem I was previously able to package, I create a Gemfile:
``` sh
mkdir coderay &&
  cd coderay &&
  cat <<EOF > Gemfile
source 'https://rubygems.org'
gem 'coderay'
EOF
```

I run bundix, and after some initial progress, it hangs for exactly 1 minute:
``` sh
$(nix-build '<nixpkgs>' -A bundix --no-out-link)/bin/bundix --magic
Fetching gem metadata from https://rubygems.org/.
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Writing lockfile to /home/ivan/Development/code/bundix-sandbox/coderay/Gemfile.lock
Fetching gem metadata from https://rubygems.org/..
Fetching version metadata from https://rubygems.org/.
```
Finally, it prints `Using bundler 1.14.6`, followed by an error:
```
Gem::RemoteFetcher::UnknownHostError: timed out
(https://rubygems.org/gems/coderay-1.1.2.gem)
An error occurred while installing coderay (1.1.2), and Bundler cannot
continue.
Make sure that `gem install coderay -v '1.1.2'` succeeds before bundling.
```

To debug, I dropped into a `nix-shell -p bundler` and ran:
```
bundler package --no-install --verbose --path vendor
```
This immediately shows:
```
HTTP GET https://index.rubygems.org/versions
HTTP 416 Range Not Satisfiable https://index.rubygems.org/versions
Bundler::HTTPError: Net::HTTPRequestedRangeNotSatisfiable
  (stack trace omitted)
```
followed by:
```
HTTP GET https://index.rubygems.org/api/v1/dependencies
HTTP 200 OK https://index.rubygems.org/api/v1/dependencies
Fetching gem metadata from https://rubygems.org/
HTTP GET https://index.rubygems.org/api/v1/dependencies
HTTP 200 OK https://index.rubygems.org/api/v1/dependencies
Query List: ["coderay"]
Query Gemcutter Dependency Endpoint API: coderay
HTTP GET https://index.rubygems.org/api/v1/dependencies?gems=coderay
HTTP 200 OK https://index.rubygems.org/api/v1/dependencies?gems=coderay
Query List: []
Fetching version metadata from https://rubygems.org/
HTTP GET https://index.rubygems.org/api/v1/dependencies
HTTP 200 OK https://index.rubygems.org/api/v1/dependencies
Query List: []
Resolving dependencies...
Using bundler 1.14.6
0:  bundler (1.14.6) from /nix/store/7wf7a3bqivikakmkhk9v1y92f6090phz-bundler-1.14.6/lib/ruby/gems/2.4.0/specifications/bundler-1.14.6.gemspec
Gem::RemoteFetcher::UnknownHostError: timed out
```
It looks like a series of requests are hitting the same endpoint ( `https://index.rubygems.org/api/v1/dependencies` ), though I'm not sure what to make of that.

**Comment by manveru** [comment]
Tried it here, no issue.

My `shell.nix` is this:

    with (import (fetchGit {
      url = https://github.com/NixOS/nixpkgs-channels;
      ref = "nixpkgs-unstable";
      rev = "255a833e841628c0b834575664eae373e28cdc27";
    }) {});
    let
      ruby = ruby_2_5;
      bundler = pkgs.bundler.override { inherit ruby; };
      bundix = pkgs.bundix.override { inherit bundler; };
      gems = bundlerEnv {
        inherit ruby;
        name = "test-gems";
        gemdir = ./.;
      };
    in stdenv.mkDerivation {
      name = "test-shell";
      buildInputs = [
        bundler
        bundix
        gems.wrappedRuby
        (lowPrio gems)
      ];
    }

In order to just run `bundix` you can comment out the `(lowPrio gems)` and `gems.wrappedRuby` lines.

The `Gemfile`:

    source 'https://rubygems.org' do
      gem 'coderay'
      gem 'rouge'
    end

 Running `bundix -l` generates this:

    {
      coderay = {
        source = {
          remotes = ["https://rubygems.org"];
          sha256 = "15vav4bhcc2x3jmi3izb11l4d9f3xv8hp2fszb7iqmpsccv1pz4y";
          type = "gem";
        };
        version = "1.1.2";
      };
      rouge = {
        source = {
          remotes = ["https://rubygems.org"];
          sha256 = "1sfhy0xxqjnzqa7qxmpz1bmy0mzcr55qyvi410gsb6d6i4ialbw3";
          type = "gem";
        };
        version = "3.1.1";
      };
    }

**Comment by ivanbrennan** [comment]
@manveru I tried the `shell.nix` you posted. I had to remove `lowPrio gems` and `gems.wrappedRuby` as they caused an error when trying to start nix-shell:
```
$ nix-shell
error: getting attributes of path '/home/ivan/Development/code/bundix-sandbox/interactive-editor/Gemfile.lock': No such file or directory
```
Did you have an existing Gemfile.lock?

Anyway, once I got into the nix-shell, I still was unable to fetch successfully:
```
[nix-shell]$ bundix -l
Fetching gem metadata from https://rubygems.org/...
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Writing lockfile to /home/ivan/Development/someDir/Gemfile.lock
Downloading /home/ivan/.cache/bundix/https_rubygems_org_gems_rouge-3_1_1_gem from https://rubygems.org/gems/rouge-3.1.1.gem
execution expired
Skipping rouge: couldn't fetch hash for rouge-3.1.1
/nix/store/7v6nwiaqrrgparp2dvfj4kyshpydqjs1-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix/source.rb:94:in `convert_rubygems'
...
Downloading /home/ivan/.cache/bundix/https_rubygems_org_gems_coderay-1_1_2_gem from https://rubygems.org/gems/coderay-1.1.2.gem
execution expired
Skipping coderay: couldn't fetch hash for coderay-1.1.2
/nix/store/7v6nwiaqrrgparp2dvfj4kyshpydqjs1-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix/source.rb:94:in `convert_rubygems'
...
```

I'm starting to wonder if this could be something about my network configuration, but that's little more than a guess.

Is it possible the request would succeed if not for the timeout? That seems unlikely for a couple small gems, but I'm running out of ideas.

**Comment by manveru** [comment]
I made a nicer `shell.nix` here for another example: https://gist.github.com/manveru/0b835aba2ec71308bdc1c540db768c1f
Usually there's no `Gemfile.lock` already, `bundix -l` will generate it along with the `gemset.nix`.

All I can think of is that there's some firewall that silently drops your connections (although that shouldn't happen with HTTPS?). It's not a problem I've seen before and can't reproduce it.

**Comment by ivanbrennan** [comment]
@manveru Thanks for your help. I haven't yet found the cause or fix, but it seems more likely to be an issue with bundler than anything else, so I'll close this issue.

NixOS has bundler at v1.14.6 (I see it was upgraded to 1.15 at one point but [reverted because that broke gitlab](https://github.com/NixOS/nixpkgs/commit/891a1662aa6cd6b2bcd2187d97f27822ed5df138)).

I also noticed the most recent bundler release ([v1.16.0](https://github.com/bundler/bundler/releases/tag/v1.16.1)) lists a bugfix:
* [avoid hanging on complex resolver errors](https://github.com/bundler/bundler/issues/6114)

which addresses a behavior like what I'm experiencing, though it sounds like a different cause.

I'll add a followup comment here if I find a resolution.

For posterity, I tried the `shell.nix` you made in that gist. My output:
```
[nix-shell:~/Development/code/bundix-sandbox/eventmachine]$ bundix -l
Fetching gem metadata from https://rubygems.org/.
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Writing lockfile to /home/ivan/Development/code/bundix-sandbox/eventmachine/Gemfile.lock
Downloading /home/ivan/.cache/bundix/https_rubygems_org_gems_eventmachine-1_2_5_gem from https://rubygems.org/gems/eventmachine-1.2.5.gem
execution expired
Skipping eventmachine: couldn't fetch hash for eventmachine-1.2.5
/nix/store/3fswkw2rhbdx40x9znm85lb37bi6bh1n-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix/source.rb:94:in `convert_rubygems'
/nix/store/3fswkw2rhbdx40x9znm85lb37bi6bh1n-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix/source.rb:6:in `convert'
/nix/store/3fswkw2rhbdx40x9znm85lb37bi6bh1n-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:48:in `convert_spec'
/nix/store/3fswkw2rhbdx40x9znm85lb37bi6bh1n-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:38:in `block in convert'
/nix/store/3fswkw2rhbdx40x9znm85lb37bi6bh1n-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:37:in `reverse_each'
/nix/store/3fswkw2rhbdx40x9znm85lb37bi6bh1n-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:37:in `with_object'
/nix/store/3fswkw2rhbdx40x9znm85lb37bi6bh1n-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/lib/bundix.rb:37:in `convert'
/nix/store/3fswkw2rhbdx40x9znm85lb37bi6bh1n-bundix-2.3.1/lib/ruby/gems/2.5.0/gems/bundix-2.3.1/bin/bundix:112:in `<top (required)>'
/nix/store/3fswkw2rhbdx40x9znm85lb37bi6bh1n-bundix-2.3.1/bin/.bundix-wrapped:18:in `load'
/nix/store/3fswkw2rhbdx40x9znm85lb37bi6bh1n-bundix-2.3.1/bin/.bundix-wrapped:18:in `<main>'
```

**Comment by ivanbrennan** [comment]
It seems this is some sort of networking issue related to rubygems.org

I noticed that although bundler is currently packaged at v1.14.6 in nixos-unstable, the default ruby (2.4.3) has bundler 1.16.1 included. I used that to run:
```
bundle package --no-install --verbose --path vendor
```
(note `bundle` vs `bundler`), and that had slightly better error output,
```
Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::UnknownHostError timed out
```
which led me to some people experiencing similar problems, including this [stackoverflow question](https://stackoverflow.com/questions/49800432/gem-cannot-access-rubygems-org), where the poster found they could successfully fetch dependencies from https://gems.ruby-china.org

I tried that and it succeeded. This let me use bundix to generate a Gemfile.lock and gemset.nix. I manually replaced https://gems.ruby-china.org with https://rubygems.org in these files before using them to build an overlay. To my surprise, rebuilding my NixOS system with this overlay included succeeded (it had no problem fetching the required gems from rubygems).

I don't know why this affected me and not many others. I can only guess there's some element of regionality at play in the network issues.

Either the network issue only affects requests that occur as part of dependency resolution or there's something about the way requests are made during a nixos-rebuild that differs from what I was doing with bundix and bundler. Still a mystery.

I also posted on an [existing thread](http://help.rubygems.org/discussions/problems/31074-timeout-error) at help.rubygems.org but haven't heard back yet.

**Comment by manveru** [comment]
Thanks for the update, maybe you could try setting your DNS to 1.1.1.1 and try with that?

**Comment by ivanbrennan** [comment]
Unfortunately, setting my DNS to 1.1.1.1 didn't change bundler's inability to fetch from rubygems. I learned a bit more about DNS though, and think I'll keep using the 1.1.1.1 nameserver. Thanks for the tip!

**Comment by ivanbrennan** [comment]
@manveru It looks like rubygems was unreachable via IPv6 and this was the cause of the problem. I don't know if we have definitive evidence for that, but someone called it out in a [support thread](http://help.rubygems.org/discussions/problems/31074-timeout-error#comment_45251177) and it seems consistent with the symptoms.
