### ISSUE TITLE
Use XDG_CACHE_HOME

### ISSUE THREAD

**Issue by pnelson** [manveru/bundix#34]
How do you feel about trying to use `XDG_CACHE_HOME` before falling back to `~/.cache`?

https://github.com/manveru/bundix/blob/e8f6acafee3d510bf0df0083ea3c0ee7c481b4cb/lib/bundix/source.rb#L25

**Comment by manveru** [comment]
I think that'd be good, do you want to make a PR?

**Comment by pnelson** [comment]
Sure, sounds good. Thank you. I'm new to NixOS so I need to wait til I get some time to sit down and figure out how to test packages. It will be a good exercise.
