### ISSUE TITLE
Cannot download from private gemserver

### ISSUE THREAD

**Issue by pmahoney** [manveru/bundix#6]
I authenticate to a private gemserver with basic auth, but bundix seems to lack a way to provide credentials.

Bundler reads credentials from the environment variable `BUNDLE_GEMS__EXAMPLE__COM` given a source of `gems.example.com`. Curl reads `.netrc` with the appropriate options. Is there any way to get `nix-prefetch-url` to use basic auth credentials?

**Comment by pmahoney** [comment]
I should note, fetchurl does handle this. Not sure if there is a more elegant way, but:

```
NIX_CURL_FLAGS="--netrc-file $HOME/.netrc" nix-build -E 'with import <nixpkgs>{}; fetchurl { url = "https://gems.example.com/gems/something-1.0.gem"; sha256 = "xxx"; }'
```

But you've got to know the sha256 ahead of time.

I did once code up something that did `nix-build ...`, scan the output for `output path ‘/xxx’ should have sha256 hash ‘wrong’, instead has ‘correct’`, then re-run `nix-build` with the correct hash. Hacky, insecure, downloads twice, but would something like that be considered?

**Comment by zimbatm** [comment]
What if you embed the credentials in the source in the Gemfile?

``` ruby
source "https://accesskey:@packagecloud.io/your/product"
```

**Comment by pmahoney** [comment]
@zimbatm that does allow me to download the gems, thanks. It would still be nice to have a way that doesn't require exposing the credentials thusly.

**Comment by manveru** [comment]
I think adding support for the environment variable makes sense, I'll see how hard that would be. Right now we're using credentials in the Gemfile, which isn't ideal. Otherwise parsing the netrc is also nice, I use that for a lot of other projects.

**Comment by pmahoney** [comment]
This is a more promising ~~technique~~hack to use `fetchurl` to download a file of unknown hash:

```
with (import <nixpkgs> {});

fetchurl {
  url = "https://raw.githubusercontent.com/NixOS/nixpkgs/master/pkgs/build-support/fetchurl/default.nix";
  sha256 = "0000000000000000000000000000000000000000000000000000";
  downloadToTemp = true;
  postFetch = ''
    PATH="$PATH:${stdenv.lib.makeBinPath [ nix ]}"

    sha256="$(nix-hash --base32 --type sha256 --flat "$downloadedFile")"
    printf "downloaded %s\nsha256-32=%s\n" "$url" "$sha256"

    file="$(dirname "$downloadedFile")/$(basename "$url")"
    mv "$downloadedFile" "$file"
    echo "adding to nix store..."
    nix-store --add "$file"

    echo "outer nix build will now fail..."
    touch "$out"
  '';
}
```

Hopefully will have time to test this to download via fetchurl, taking advantage of its ability to apply `NIX_CURL_FLAGS`.
