### ISSUE TITLE
Add trailing newline to gemset.nix

### ISSUE THREAD

**Issue by Mic92** [manveru/bundix#77]
Our editorconfig in nixpkgs has this as a check: 
https://github.com/NixOS/nixpkgs/pull/108641/checks?check_run_id=1660939525#step:5:8

**Comment by SuperSandro2000** [comment]
@mic92 can we release a new version with this change?

**Comment by Mic92** [comment]
https://github.com/nix-community/bundix/releases/tag/2.5.1
