### ISSUE TITLE
Installing nokogiri fails to install on NixOS 16.03

### ISSUE THREAD

**Issue by alexkehayias** [manveru/bundix#9]
When installing rails using bundix on NixOS 16.03 with the following Nix expression, nokogiri fails to install because it `Could not find 'pkg-config' (~> 1.1.7) among 5 total gem(s)`. The workaround is to first `gem install pkg-config` inside `nix-shell` and then update the Nix expression with `bundlerEnv`. It either looks like dependencies are not installed in the correct order or the gem path is getting mangled somewhere? Any help on where to look would be greatly appreciated!
## Gemfile

```
source 'https://rubygems.org'

gem 'rails'
```
## default.nix

```
with (import <nixpkgs> {});

let
  rubyenv = bundlerEnv {
    name = "rb";
    inherit ruby;
    gemfile = ./Gemfile;
    lockfile = ./Gemfile.lock;
    gemset = ./gemset.nix;
  };
in stdenv.mkDerivation {
  name = "myProject";
  version = "0.0.1";

  buildInputs = [
    stdenv
    git

    # Ruby deps
    ruby
    bundler
    bundix

    # Rails deps
    clang
    libxml2
    libxslt
    readline
    sqlite
    openssl

    rubyenv
  ];

  shellHook = ''
    export PS1="[myProject] > "
    export LIBXML2_DIR=${pkgs.libxml2}
    export LIBXSLT_DIR=${pkgs.libxslt}
  '';
}
```

**Comment by zimbatm** [comment]
Hi, this is a known issue that's been fixed in unstable and will appear in the next release (which is coming soon!).

~~See NixOS/nixpkgs@6ae57b1b634d2145f72c1742685695e7192102ba~~
Sorry wrong link: https://github.com/NixOS/nixpkgs/pull/18099

**Comment by alexkehayias** [comment]
Thanks didn't realize that was the problem. Feel free to close unless you
want to wait for the official release to be sure. I'm happy to do all the
testing once it's released.

**Comment by zimbatm** [comment]
No worries, actually the PR was sitting there so thanks to you it's merged now :)

I'll close this issue for now but feel free to re-open (or ping me if it's not possible)
